[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.8.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "NLtoSQL_Project.settings"
  DEBUG = "0"
  DJANGO_SECURE_SSL_REDIRECT = "true"
  DJANGO_SESSION_COOKIE_SECURE = "true"
  DJANGO_CSRF_COOKIE_SECURE = "true"
  DJANGO_SECURE_HSTS_SECONDS = "2592000"
  DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS = "true"
  DJANGO_SECURE_HSTS_PRELOAD = "true"