[build]
  command = """
    export PATH="/opt/buildhome/.pyenv/versions/3.8.12/bin:$PATH"
    pyenv local 3.8.12
    python -m venv .venv
    . .venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.8.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "NLtoSQL_Project.settings"
  DEBUG = "0"