services:
  - type: web
    name: NLtoSQL_Project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn NLtoSQL_Project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString