# Generated by Django 5.0.6 on 2024-08-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="databaseupload",
            old_name="supabase_path",
            new_name="b2_path",
        ),
    ]
