# Generated by Django 5.0.6 on 2024-06-16 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0002_queryhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("dbname", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("connection_date", models.DateTimeField(auto_now_add=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NLtoSQL.databaseupload",
                    ),
                ),
            ],
        ),
    ]
