# Generated by Django 5.0.6 on 2024-08-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0002_rename_supabase_path_databaseupload_b2_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="databaseupload",
            old_name="b2_path",
            new_name="b2_file_key",
        ),
    ]
