# Generated by Django 5.0.6 on 2024-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0003_rename_b2_path_databaseupload_b2_file_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusage",
            name="user_input_request_context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
