# Generated by Django 5.0.6 on 2024-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0004_alter_databaseconnection_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconnection",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
