# Generated by Django 5.0.6 on 2024-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0004_alter_apiusage_user_input_request_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusage",
            name="model_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
