# Generated by Django 5.0.6 on 2024-06-17 08:35

import NLtoSQL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0005_alter_databaseconnection_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasetype",
            name="hostType",
            field=models.CharField(
                blank=True, default="NULL", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="databaseupload",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=NLtoSQL.models.get_upload_path
            ),
        ),
    ]
