# Generated by Django 5.0.6 on 2024-06-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0009_alter_databaseupload_hosttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryhistory",
            name="database",
            field=models.ForeignKey(
                default="N/A",
                on_delete=django.db.models.deletion.CASCADE,
                to="NLtoSQL.databaseupload",
            ),
        ),
    ]
