# Generated by Django 5.0.6 on 2024-06-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0010_alter_queryhistory_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryhistory",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="NLtoSQL.databaseupload"
            ),
        ),
    ]
