# Generated by Django 5.0.6 on 2024-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0006_databasetype_hosttype_alter_databaseupload_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databasetype",
            name="hostType",
        ),
        migrations.AddField(
            model_name="databaseupload",
            name="hostType",
            field=models.CharField(
                blank=True, default="N/A", max_length=255, null=True
            ),
        ),
    ]
