# Generated by Django 5.0.6 on 2024-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0007_remove_databasetype_hosttype_databaseupload_hosttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseupload",
            name="hostType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("localhost", "Localhost"),
                    ("cloud", "Cloud Host"),
                    ("os_file", "OS File Host"),
                    ("Self-Hosted", "Self Hosted"),
                    ("other_hosts", "Other Hosts"),
                    ("N/A", "N/A"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
