# Generated by Django 5.0.6 on 2024-06-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0008_alter_databaseupload_hosttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseupload",
            name="hostType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("localhost", "Local Host"),
                    ("cloud", "Cloud Host"),
                    ("os_file", "OS File Host"),
                    ("Self-Hosted", "Self Hosted"),
                    ("other_hosts", "Other Hosts"),
                    ("N/A", "N/A"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queryhistory",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="NLtoSQL.databaseupload"
            ),
        ),
    ]
