# Generated by Django 5.0.6 on 2024-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0011_alter_queryhistory_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="query_nl_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
