# Generated by Django 5.0.6 on 2024-07-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0012_queryhistory_query_nl_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusage",
            name="user_input_request_context",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
