# Generated by Django 5.0.6 on 2024-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0013_apiusage_user_input_request_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusage",
            name="model_response",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
