# Generated by Django 5.0.6 on 2024-07-17 07:24
import NLtoSQL.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0014_apiusage_model_response"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       migrations.AddField(
    model_name="databaseupload",
    name="file",
    field=models.FileField(upload_to=NLtoSQL.models.get_upload_path, null=True),
        )
       
    ]
