# Generated by Django 5.0.6 on 2024-07-23 05:49

import NLtoSQL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NLtoSQL", "0016_remove_databaseupload_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseupload",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=NLtoSQL.models.get_upload_path
            ),
        ),
    ]
